### ISSUE TITLE
unable to get the pre-compiled binaries

### ISSUE THREAD

**Issue by liyigerry** [tonigi/vmd_plumed#7]
I follow the tutorial
> pre-compiled binaries for Win32 (driver.exe and plumed.exe) 

But the url for download is not available. Please provide the right urls for the user.

Thanks.

**Comment by tonigi** [comment]
Hi, somehow did not get a notice for this issue. Urls fixed in the latest release; binaries available at https://github.com/tonigi/vmd_plumed/tree/gh-pages/binaries .
